sudo: required
language: python
python: 3.6-dev

services:
  - postgresql
  - redis-server
  - rabbitmq

env:
  global:
    - ARMONAUT_ENV=development
    - SECRET_KEY=travisci
    - DATABASE_URL=postgresql://postgres@localhost:5432/armonaut
    - REDIS_URL=redis://localhost:6379/0
    - AMQP_URL=amqp://guest@localhost:5672//
  matrix:
    - SCRIPT=lint
    - SCRIPT=unit
    - SCRIPT=integration DRIVER=Firefox
    - SCRIPT=integration DRIVER=Chrome

before_install:
  - psql -c 'create database armonaut;' -U postgres

install:
  - python -m pip install -r requirements.txt -r dev-requirements.txt

  # Installing drivers for Selenium testing
  - |
    if [ "$SCRIPT" == "integration" ]; then
      if [ "$DRIVER" == "Firefox" ]; then
        sudo ./dev/install-firefox-driver
      fi;
      if [ "$DRIVER" == "Chrome" ]; then
        sudo ./dev/install-chrome-driver
      fi;
    fi;

script:
  - |
    if [ "$SCRIPT" == "unit" ]; then
      pytest tests/unit/
    elif [ "$SCRIPT" == "integration" ]; then
      pytest tests/integration/ --driver $DRIVER
    elif [ "$SCRIPT" == "lint" ]; then
      flake8 armonaut/ --max-line-length=99
    fi
  - |
    if [ "$SCRIPT" != "lint" ]; then
      coverage report -m
    fi

after_success:
  - |
    if [ "$SCRIPT" != "lint" ]; then
      codecov
    fi

notifications:
  email: false
