sudo: required
language: python
python: 3.6-dev

services:
  - postgresql
  - redis-server

env:
  global:
    - ARMONAUT_ENV=development
    - SECRET_KEY=travisci
    - DATABASE_URL=postgresql://postgres@localhost:5432/armonaut
    - REDIS_URL=redis://localhost:6379/0
  matrix:
    - SCRIPT=lint
    - SCRIPT=unit
    - SCRIPT=integration

before_install:
  - psql -c 'create database armonaut;' -U postgres

install:
  - python -m pip install -r requirements.txt -r dev-requirements.txt

script:
  - |
    if [ "$SCRIPT" == "unit" ]; then
      pytest tests/unit/
    elif [ "$SCRIPT" == "integration" ]; then
      pytest tests/integration/
    elif [ "$SCRIPT" == "lint" ]; then
      flake8
    fi
  - |
    if [ "$SCRIPT" != "lint" ]; then
      coverage report -m
    fi

after_success:
  - |
    if [ "$SCRIPT" != "lint" ]; then
      codecov
    fi

notifications:
  email: false
