sudo: required
language: python
python: 3.6-dev

services:
  - postgresql
  - redis-server
  - rabbitmq

env:
  global:
    - APP_SETTINGS=config.TestingConfig
    - SECRET_KEY=travisci
    - DATABASE_URL=
    - REDIS_URL=
    - AMQP_URL=://
  matrix:
    - SCRIPT=lint
    - SCRIPT=unit

before_install:
  - psql -c 'create database armonaut;' -U postgres

install:
  - python -m pip install -r requirements.txt -r dev-requirements.txt

script:
  - |
    if [ "$SCRIPT" == "unit" ]; then
      pytest tests/
    elif [ "$SCRIPT" == "lint" ]; then
      flake8 armonaut/
    fi

after_success:
  - |
    if [ "$SCRIPT" != "lint" ]; then
      codecov
    fi
