version: '3'

services:
  database:
    image: postgres:9.6
    environment:
      POSTGRES_DB: armonaut

  redis:
    image: redis:latest

  rabbitmq:
    image: rabbitmq:latest

  web:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8080 armonaut.wsgi:app
    volumes:
      - ./dev:/opt/armonaut/dev:z
      - ./armonaut:/opt/armonaut/armonaut:z
      - ./tests:/opt/armonaut/tests:z
    env_file: dev/docker-environment
    ports:
      - '80:8080'
    links:
      - database
      - redis
      - rabbitmq

  worker:
    build:
      context: .
    environment:
      C_FORCE_ROOT: '1'
    command: celery -A armonaut.celery.app worker -B -S redbeat.RedBeatScheduler -l info
    volumes:
      - ./dev:/opt/armonaut/dev:z
      - ./armonaut:/opt/armonaut/armonaut:z
      - ./tests:/opt/armonaut/tests:z
    env_file: dev/docker-environment
    links:
      - database
      - redis
      - rabbitmq
      - smtp

  smtp:
    build:
      context: .
    command: python3 /opt/armonaut/dev/smtp.py 0.0.0.0:2525
    volumes:
      - ./dev/smtp.py:/opt/armonaut/dev/smtp.py:z
    ports:
      - '2525:2525'
