version: '3'

services:
  database:
    image: postgres:10.1
    environment:
      POSTGRES_DB: armonaut

  redis:
    image: redis:latest

  web:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8080 armonaut.wsgi:app
    env_file: dev/docker-environment
    ports:
      - '80:8080'
    links:
      - database
      - redis

  worker:
    build:
      context: .
    environment:
      C_FORCE_ROOT: '1'
    command: celery -A armonaut.celery.app worker -B -S redbeat.RedBeatScheduler -l info
    env_file: dev/docker-environment
    links:
      - database
      - redis
      - smtp

  smtp:
    build:
      context: .
    command: python3 /opt/armonaut/dev/smtp.py 0.0.0.0:2525
    ports:
      - '2525:2525'
