#!/bin/bash
# Script for installing Firefox and Geckodriver for Selenium tests

# Installing Firefox
sudo apt-get install -y firefox

# Installing Geckodriver
curl -sfL https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz -o /tmp/geckodriver.tar.gz
tar -xzvf /tmp/geckodriver.tar.gz
rm /tmp/geckodriver.tar.gz
chmod +x geckodriver
mv geckodriver /usr/local/bin
